### ISSUE TITLE
run Rainloop

### ISSUE THREAD

**Issue by amirarabi** [jprjr/docker-rainloop#1]
Hi
i run this command but can not run Rainloop on port 9000

docker pull jprjr/rainloop
 docker run -d -p 9000 -v /var/lib/rainloop/data:/var/lib/rainloop/data jprjr/rainloop

Thanks

**Comment by jprjr** [comment]
Port 9000 is the port PHP-FPM uses for FastCGI connections - I don't think you can connect to port 9000 with your web browser, you need to setup NGINX or Apache in front of it.

You can either run an NGINX or Apache container and connect it to this container; or you can run NGINX in the container by setting the NGINX environment variable to 1. So something like:

`docker run -d -p 80:80 -e NGINX=1 -v /var/lib/rainloop/data:/var/lib/rainloop/data jprjr/rainloop`
